### ISSUE TITLE
Further Examples

### ISSUE THREAD

**Issue by Dokotela** [HL7/ImmunizationFHIRDS#15]
As I was going through the examples, I was wondering if we could post an example of an invalid dose with the reason? There are currently only valid doses posted, but I think it would be helpful to show some using the [status codes](https://terminology.hl7.org/1.0.0/CodeSystem-immunization-evaluation-dose-status.html) with the [status reasons](http://hl7.org/fhir/us/ImmunizationFHIRDS/CodeSystem/StatusReason). (especially given [this change](https://github.com/HL7/ImmunizationFHIRDS/issues/12)).

**Comment by Dokotela** [comment]
Also, and a very nitpicking observation. The [ForecastStatus Codes](http://hl7.org/fhir/us/ImmunizationFHIRDS/CodeSystem/ForecastStatus) are in camel case and the [status reason codes](http://hl7.org/fhir/us/ImmunizationFHIRDS/CodeSystem/StatusReason) are not. Should we pick one just for consistency?

**Comment by csnewman88** [comment]
I made both suggested changes and pushed to the AIRA github site so that we could review them before pushing to the official HL7 build site.

**Comment by nathanbunker** [comment]
I have pushed this to here for review: http://florence.immregistries.org/ImmunizationFHIRDS/site/index.html

**Comment by Dokotela** [comment]
That was exactly what I was hoping for, thanks!

**Comment by csnewman88** [comment]
We can't apply these changes for the initial publication (too many groups have already approved the publication request based on the original content), but we can make the changes in a future release. Jira tickets have been created:
https://jira.hl7.org/browse/FHIR-28145
https://jira.hl7.org/browse/FHIR-28146
