### ISSUE TITLE
Birthdate

### ISSUE THREAD

**Issue by Dokotela** [HL7/ImmunizationFHIRDS#16]
I may have missed it if it was defined elsewhere, but the [StructureDefinition: ImmDSPatient](http://build.fhir.org/ig/HL7/ImmunizationFHIRDS/StructureDefinition-immds-patient.html) doesn't include any mention of a birthdate. I think it probably needs to be added and made required.

**Comment by csnewman88** [comment]
If you look at the differential tab of the profile, it adds a constrain to require the birth date.

![image](https://user-images.githubusercontent.com/17408249/88400981-c016ef00-cd8e-11ea-9da1-8e1665b5996d.png)

**Comment by Dokotela** [comment]
My mistake, thanks!
